# Week 1 results

This week I have been able to install the R-studio and Git desktop tool. I already had my own Github account. I managed to fork the given Github repository and clone it on my own laptop. I have made some changes on the files cloned (with R-studio) and I also generated a public web page in github that will later be my learning diary (this document).

I learned some basic R - language and how to render the contents added on the R markdown file in the viewer. I had some trouble in getting the R-studio to render my work but I think it was because I did not have an R-studio project created at first. 

## Useful links and resources
### Task description and course pages
#### Course page (MOOC)
https://mooc.helsinki.fi/course/view.php?id=158

#### First week task
https://mooc.helsinki.fi/course/view.php?id=158#section-1

#### Data camp exercise
https://www.datacamp.com/courses/r-short-and-sweet

#### Course diary instructions
https://emmakarolina.github.io/instructions/#the_course_diary_web_page

### My results

#### My github repository
https://github.com/salopant/IODS-project

#### My learning diary (this file)
https://salopant.github.io/IODS-project

